databases:
  - name: cs2_killtracker_database
    databaseName: cs2_killtracker_database
    user: sam
    plan: free

services:
  - type: web
    name: cs2_killtracker_webserver
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cs2_killtracker_database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
